# ---------------------------------------------------------
# Agent 4 — Python REPL Runner (Option C: _df_json-based)
# ---------------------------------------------------------

from __future__ import annotations
from typing import TypedDict, Optional
import io
import json
import traceback

import matplotlib.pyplot as plt
from dotenv import load_dotenv
from langchain_experimental.tools.python.tool import PythonREPLTool
from langchain_core.runnables import RunnableLambda
from langgraph.graph import StateGraph, END

load_dotenv()


class RunnerState(TypedDict, total=False):
    code: Optional[str]
    df_json: Optional[str]
    image_bytes: Optional[bytes]
    error: Optional[str]


def clean_code_fences(code: str) -> str:
    code = code.strip()
    if code.startswith("```"):
        parts = code.split("```")
        if len(parts) >= 2:
            code = parts[1]
    code = code.replace("```python", "").replace("```", "")
    return code.strip()


DANGEROUS_PATTERNS = [
    "import os",
    "os.",
    "subprocess",
    "shutil",
    "eval(",
    "exec(",
    "__import__",
    "open(",
    "sys.",
    "input(",
]


def is_code_safe(code: str) -> bool:
    lower = code.lower()
    for pat in DANGEROUS_PATTERNS:
        if pat in lower:
            return False
    return True


# Persistent Python REPL
python_repl = PythonREPLTool()


def node_run_code(state: RunnerState) -> RunnerState:
    raw_code = state.get("code") or ""
    df_json = state.get("df_json") or ""

    if not raw_code:
        return {"error": "No visualization code provided."}

    code = clean_code_fences(raw_code)

    if not is_code_safe(code):
        return {"error": "❌ Unsafe or disallowed code detected. Execution blocked."}

    # Reset figures in this process
    plt.close("all")

    # 1) Preload _df_json into the REPL
    try:
        # df_json is a Python string; json.dumps will produce a safe Python literal
        df_json_literal = json.dumps(df_json)
        assign_code = f"_df_json = {df_json_literal}"
        python_repl.run(assign_code)
    except Exception:
        return {"error": "Failed to inject _df_json into Python REPL."}

    # 2) Execute the full script generated by Agent 2
    try:
        python_repl.run(code)
    except Exception:
        return {"error": traceback.format_exc()}

    # 3) Capture matplotlib figure
    fig = plt.gcf()
    if fig and fig.get_axes():
        buf = io.BytesIO()
        fig.savefig(buf, format="png", bbox_inches="tight")
        buf.seek(0)
        plt.close(fig)
        return {"image_bytes": buf.getvalue(), "error": None}

    return {"error": "Code executed but produced no figure."}


builder = StateGraph(RunnerState)
builder.add_node("run_code", RunnableLambda(node_run_code))
builder.set_entry_point("run_code")
builder.add_edge("run_code", END)

runner_app = builder.compile()
