import streamlit as st
import pandas as pd
import json

from agent_sql_generator import sql_agent_app
from agent_code_generation import viz_agent_app
from agent_code_validator import validator_app
from agent_code_runner import runner_app


st.set_page_config(page_title="AI SQL + Viz + Validator", layout="wide")
st.title("🤖 AI SQL → Visualization Pipeline (All 4 Agents)")


# ------------------------------------------------------
# USER INPUT
# ------------------------------------------------------
question = st.text_input("Ask a question about the robot vacuum DB:")

# Display stored session state (for debugging UI)
with st.expander("📦 Session State Snapshot"):
    st.json({k: str(v)[:200] for k, v in st.session_state.items()})


# ------------------------------------------------------
# RUN AGENT 1 — SQL GENERATOR
# ------------------------------------------------------
if st.button("Run Agent 1 (Generate SQL & DataFrame)"):

    st.subheader("🔵 Step 1 — Agent 1 Running...")

    state = sql_agent_app.invoke({"question": question})

    # --- SHOW SQL ---
    st.subheader("🔍 SQL Generated by Agent 1:")
    st.code(state.get("sql", "No SQL returned"), language="sql")

    # --- ERROR OR DATA ---
    if state.get("error"):
        st.error(state["error"])
        st.session_state.df_json = None
        st.session_state.sql_code = None
    else:
        df = state.get("df")

        if isinstance(df, pd.DataFrame):
            st.success("SQL executed successfully!")
            st.dataframe(df)

            st.session_state.df_json = df.to_json(orient="records")
            st.session_state.sql_code = state.get("sql")
        else:
            st.warning("No DataFrame returned.")
            st.session_state.df_json = None


# ------------------------------------------------------
# RUN AGENT 2 — VIZ CODE GENERATOR
# ------------------------------------------------------
if st.button("Run Agent 2 (Generate Visualization Code)"):

    st.subheader("🟣 Step 2 — Agent 2 Running...")

    if "df_json" not in st.session_state or not st.session_state.df_json:
        st.error("Run Agent 1 first to generate a DataFrame.")
    else:

        viz_state = viz_agent_app.invoke({
            "df_json": st.session_state.df_json,
            "question": question
        })

        # --- SHOW GENERATED CODE ---
        st.subheader("🎨 Visualization Code (Agent 2):")
        st.code(viz_state.get("viz_code", ""), language="python")

        # --- SAVE STATE ---
        st.session_state.viz_code = viz_state.get("viz_code")
        st.session_state.raw_viz_state = viz_state  # DEBUG PANEL

        # Show DF preview
        df_preview = pd.read_json(st.session_state.df_json)
        with st.expander("📄 DataFrame Preview (Used by Agent 2)"):
            st.dataframe(df_preview)


# ------------------------------------------------------
# RUN AGENT 3 — CODE VALIDATOR
# ------------------------------------------------------
if st.button("Run Agent 3 (Validate Code)"):

    st.subheader("🟠 Step 3 — Agent 3 Running...")

    if "viz_code" not in st.session_state or not st.session_state.viz_code:
        st.error("Run Agent 2 first to generate visualization code.")
    else:

        validation = validator_app.invoke({
            "code": st.session_state.viz_code,
            "df_json": st.session_state.df_json,
        })

        st.subheader("🧪 Agent 3 — Validation Result")

        if validation.get("is_valid"):
            st.success("✅ Visualization code is VALID!")
        else:
            st.error("❌ Visualization code is NOT valid.")

        st.write(validation.get("feedback", ""))

        # store in session state
        st.session_state.validation = validation

        # DEBUG
        with st.expander("🔍 Raw Validator Output"):
            st.json(validation)


# ------------------------------------------------------
# RUN AGENT 4 — EXECUTE VISUALIZATION
# ------------------------------------------------------
if st.button("Run Agent 4 (Execute Validated Code)"):

    st.subheader("🟢 Step 4 — Agent 4 Running...")

    validation = st.session_state.get("validation")

    if not validation or not validation.get("is_valid"):
        st.error("Code is not valid. Fix it first using Agent 3.")
    else:
        result = runner_app.invoke({
            "code": st.session_state.viz_code,
            "df_json": st.session_state.df_json,
        })

        if result.get("error"):
            st.error(result["error"])
        else:
            st.subheader("📊 Visualization Output")
            st.image(result["image_bytes"])

            # DEBUG SHOW RAW RUNNER OUTPUT
            with st.expander("🧩 Raw Runner State"):
                st.json({k: str(v)[:250] for k, v in result.items()})
